#!/bin/sh
#
# Copyright (c) 2017-2018, 2020 The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#    # Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    # Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#    # Neither the name of The Linux Foundation, nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# Location Hal Daemon - init.d script for /usr/bin/location_hal_daemon

set -e
wait_for_dir_mount() {
    while ! [ -d /dev ]
    do
        echo "waiting for /dev to mount"
    done
}

create_set_folder() {
    if [ ! -d "${1}" ]
    then
        mkdir -p "${1}"
        chown -R "${2}" "${1}"
        chmod "${3}" "${1}"
    fi
}

# for location hal daemon
case "$1" in
  start)
        echo -n "Starting location_hal_initializer" > /dev/kmsg
        wait_for_dir_mount
        create_set_folder "/dev/socket/location" "gps:gps" 755
        create_set_folder "/dev/socket/loc_client" "gps:locclient" 775
        create_set_folder "/dev/socket/location/ehub" "gps:gps" 755
        echo "Done creating folders for location hal daemon"
        ;;
  stop)
        echo -n "Stopping location_hal_initializer" > /dev/kmsg
        ;;
  restart)
        $0 stop
        sleep 1
        $0 start
        ;;
  *)
        echo -n "Usage location_hal_initializer { start | stop | restart }" >&2
        exit 1
        ;;
esac

exit 0
